### ISSUE TITLE
Recruit helpers

### ISSUE THREAD

**Issue by pgmccann** [StAResComp/2019-09-23-standrews#4]
We need to recruit helpers and add their details to the webpage

---

Thanks for contributing! If this contribution is for instructor training, please send an email to checkout@carpentries.org with a link to this contribution so we can record your progress. You’ve completed your contribution step for instructor checkout just by submitting this contribution.  

If this issue is about a specific episode within a lesson, please provide its link or filename.

Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please contact Kate Hertweck (k8hertweck@gmail.com).  

---

**Comment by pgmccann** [comment]
We have 3 helpers, recruited by @alex-konovalov. Is that enough, given the number of instructors?

**Comment by olexandr-konovalov** [comment]
So far all newly recruited helpers are new to the Carpentries - would be good to have at least one who had helped before as well.

**Comment by pgmccann** [comment]
Given that there should always be at least one instructor acting as a helper at any point in time, I think we might be OK.
