### ISSUE TITLE
Confirm instructors

### ISSUE THREAD

**Issue by pgmccann** [StAResComp/2019-09-23-standrews#5]
We need to confirm who is instructing. I've put Alex, me and Michael down, as I think we previously indicated we were likely to be available - this is not to discount Isla (and are we inviting Peter?). If anyone really wants to teach a particular lesson, or isn't available, please speak up.

---

Thanks for contributing! If this contribution is for instructor training, please send an email to checkout@carpentries.org with a link to this contribution so we can record your progress. You’ve completed your contribution step for instructor checkout just by submitting this contribution.  

If this issue is about a specific episode within a lesson, please provide its link or filename.

Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please contact Kate Hertweck (k8hertweck@gmail.com).  

---

**Comment by pgmccann** [comment]
I'm happy to do Shell and/or Git. Can stretch to Python given enough notice. Would like to teach at least one lesson after sitting out the last one.

**Comment by mtorpey** [comment]
I'd be happy to teach anything, preferring Shell or Git -- however, I don't yet know what lecturing responsibilities I'll have, so might be unavailable for part of the course.  I assume @alex-konovalov is the same.

I'll certainly update here when I know more!

**Comment by olexandr-konovalov** [comment]
Same here. Hopefully we will have a complete picture of our schedule shortly and will be able to plan who does what.

**Comment by pgmccann** [comment]
For now, should we go with me teaching Shell and Git and @peterjc teaching Python?

**Comment by peterjc** [comment]
Happy to do either of the Python afternoons (or split them alternating topics with a second instructor?).

Are you hoping I would do both Python sessions?

**Comment by pgmccann** [comment]
@peterjc our problem at the moment is that Alex and Michael can't confirm availability for any of the sessions. Would you feel up to teaching both Python sessions if necessary (hopefully it isn't)?

**Comment by peterjc** [comment]
I'd prefer not to do both at this point with my SWC experience.

I take it @widdowquinn isn't available for either afternoon?

**Comment by pgmccann** [comment]
OK, no problem, we'll sort something out. Leighton's settling into his new role in Glasgow.

**Comment by olexandr-konovalov** [comment]
Me and @mtorpey were teaching Python lesson before, I hope at least one of us will be able. Still waiting to hear my tutorials schedule.

**Comment by mtorpey** [comment]
I'm still waiting to hear about tutorials as well.  Will update as soon as I can! :)

**Comment by mtorpey** [comment]
Tutorials haven't quite been confirmed yet, but the provisional schedule looks really bad.  I'll be busy all Monday morning, part of Monday afternoon, and part of Tuesday morning.  I might be able to make Tuesday afternoon, but I think the safest bet is to assume I'm not going to be able to come at all.

Sorry about that!

**Comment by pgmccann** [comment]
Let's never do a late September workshop again.

@peterjc which part of the Python lesson were you planning to teach?

**Comment by peterjc** [comment]
I taught the first half of the Python material last time, but should be OK with either half - hopefully @alex-konovalov's schedule allows him to attend at least one afternoon.

**Comment by pgmccann** [comment]
@peterjc , @alex-konovalov has classes both afternoons.

I could teach some Python, but as (a) I haven't taught it before and (b) I'm teaching Git on the second morning, I'd rather do the first half, if that's OK. Are you planning to work from http://swcarpentry.github.io/python-novice-inflammation or http://swcarpentry.github.io/python-novice-gapminder/?

**Comment by peterjc** [comment]
https://swcarpentry.github.io/python-novice-inflammation/

**Comment by pgmccann** [comment]
OK, so if I take sections 1-4 of that on Monday afternoon, are you OK to continue from there on Tuesday?

**Comment by peterjc** [comment]
OK, and maybe if you have time 5 (Making Choices) on the first day?

**Comment by pgmccann** [comment]
Yes, I'll prepare that too - just looking at the estimated timings, that might be pushing it slightly. I'll try and get it done, but please be ready to pick it up on Tuesday if necessary.

**Comment by pgmccann** [comment]
So, the final schedule:

- Monday AM: Shell - @alex-konovalov 
- Monday PM: Python 1 - @pgmccann 
- Tuesday AM: Git - @pgmccann 
- Tuesday PM: Python 2 - @peterjc

**Comment by widdowquinn** [comment]
Good luck, guys! Sounds like your timetabling is a nightmare. Seems to be true everywhere ;)
